name: 'Tofu Destroy'
 
on:
  # push:
  #   paths:
  #     - 'terraform/**'
  #   branches: [ "main" ]
  workflow_dispatch:
 
jobs:
  tofu:
    name: 'Tofu'
    env:
      TF_VAR_b2_application_key_id: ${{ secrets.b2_application_key_id }}
      TF_VAR_b2_application_key: ${{ secrets.b2_application_key }}
      TF_VAR_linode_token: ${{ secrets.linode_token }}
      TF_VAR_authorized_users: ${{ vars.authorized_users }}

    runs-on: ubuntu-latest
    # environment: # No Environments available in Private (Free) Repo
 
    defaults:
      run:
        working-directory: ./terraform/

    steps:
    - uses: actions/checkout@v3
    - uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.8.2
        tofu_wrapper: false
    
    - name: Tofu fmt
      id: fmt
      run: tofu fmt -check
      continue-on-error: true
    
    - name: Tofu Init
      id: init
      run: tofu init
      continue-on-error: false
  
    - name: Tofu Destroy
      id: apply
      run: tofu destroy -no-color -auto-approve
      continue-on-error: false